version: 2
jobs:
  build:
    docker:
      - image: opspresso/builder
    steps:
      - checkout
      - run:
          name: Check versions
          command: ./version.sh $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME $GITHUB_TOKEN

workflows:
  version: 2
  apply:
    jobs:
      - build
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
