version: 2
jobs:
  report:
    docker:
      - image: opspresso/builder
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-versions-${CIRCLE_PREVIOUS_BUILD_NUM}
          - v1-versions-
      - run:
          name: Check Versions
          command: ./report.sh $SLACK_TOKEN
      - store_artifacts:
          path: .versions
      - save_cache:
          paths:
            - .versions
          key: v1-versions-${CIRCLE_BUILD_NUM}

workflows:
  version: 2
  apply:
    jobs:
      - report
  nightly:
    jobs:
      - report
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
