version: 2
jobs:
  build:
    docker:
      - image: opspresso/builder
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-versions
      - run:
          name: Check Versions
          command: ./version.sh $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME "$GITHUB_TOKEN" "$SLACK_TOKEN"
      - save_cache:
          paths:
            - ./.versions
          key: v1-versions

workflows:
  version: 2
  apply:
    jobs:
      - build
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
