version: 2
jobs:
  report:
    docker:
      - image: opspresso/builder
    steps:
      - checkout
      - run:
          name: Check Versions
          command: ./report.sh $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME $GITHUB_TOKEN
      - store_artifacts:
          path: .versions

workflows:
  version: 2
  apply:
    jobs:
      - report
  nightly:
    jobs:
      - report
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
