version: 2
jobs:
  report:
    docker:
      - image: opspresso/builder
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          name: Check Charts Versions
          command: ./report.sh $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME $SLACK_TOKEN
      - store_artifacts:
          path: .versions
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - target/*
  release:
    docker:
      - image: circleci/golang
    steps:
      - attach_workspace:
          at: workspace
      - run:
          name: Release
          command: |
            VERSION=$(cat workspace/target/VERSION)
            echo ${VERSION}
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} workspace/target/

workflows:
  version: 2
  apply:
    jobs:
      - report
      - release:
          requires:
            - report
  nightly:
    jobs:
      - report
      - release:
          requires:
            - report
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
