name: Build-Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Check Version
        uses: opspresso/action-kube@master
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          bash ./report.sh

      - name: Release
        uses: opspresso/action-builder@master
        with:
          args: --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASSET_PATH: ./target/release
